# This module provides a repo for each requires-dependency in your conanfile.
# It's generated by the BazelDeps. Include the generated module snippet from your
# MODULE.bazel file:
# include("//conan:conan_deps.MODULE.bazel")
load(":conan_deps_repo_rules.bzl", "conan_dependency_repo")

def _load_dependencies_impl(mctx):
    conan_dependency_repo(
        name = "fmt",
        package_path = "/home/jegan/.conan2/p/b/fmta46fc51ef2e5e/p",
        build_file_path = "/home/jegan/bazel-sep-2026/Day3/bazel-with-conan/conan/fmt/BUILD.bazel",
    )

    return mctx.extension_metadata(
        # It will only warn you if any direct
        # dependency is not imported by the 'use_repo' or even it is imported
        # but not created. Notice that root_module_direct_dev_deps can not be None as we
        # are giving 'all' value to root_module_direct_deps.
        # Fix the 'use_repo' calls by running 'bazel mod tidy'
        root_module_direct_deps = 'all',
        root_module_direct_dev_deps = [],

        # Prevent writing function content to lockfiles:
        # - https://bazel.build/rules/lib/builtins/module_ctx#extension_metadata
        # Important for remote build. Actually it's not reproducible, as local paths will
        # be different on different machines. But we assume that conan works correctly here.
        # IMPORTANT: Not compatible with bazel < 7.1
        reproducible = True,
    )

conan_extension = module_extension(
    implementation = _load_dependencies_impl,
    os_dependent = True,
    arch_dependent = True,
)